# Generated by Django 4.2.18 on 2025-02-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('first_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('first_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('first_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('last_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('last_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('last_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('position_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('image', models.ImageField(default='rasm.png', upload_to='employees/images/', verbose_name='Image')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/', null=True, verbose_name='Instagram link URL')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/', null=True, verbose_name='Facebook link URL')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/', null=True, verbose_name='Telegram link URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('slug_uz', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('slug_ru', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_uz', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_ru', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('category_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('category_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('category_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('events', models.CharField(choices=[('ekspeditsiya', 'Ekspeditsiya'), ('konferensiyalar', 'konferensiya'), ('amaliy seminar', 'Amaliy seminar'), ('geologik sayohatlar', 'Geologik sayohatlar'), ('vebinarlar', 'Vebinarlar'), ('kashfiyotlar', 'Kashfiyotlar'), ('treninglar', 'Treninglar'), ('forumlar', 'Forumlar'), ('ilmiy taqdimotlar', 'Ilmiy taqdimotlar')], max_length=100, verbose_name='Events')),
                ('events_uz', models.CharField(choices=[('ekspeditsiya', 'Ekspeditsiya'), ('konferensiyalar', 'konferensiya'), ('amaliy seminar', 'Amaliy seminar'), ('geologik sayohatlar', 'Geologik sayohatlar'), ('vebinarlar', 'Vebinarlar'), ('kashfiyotlar', 'Kashfiyotlar'), ('treninglar', 'Treninglar'), ('forumlar', 'Forumlar'), ('ilmiy taqdimotlar', 'Ilmiy taqdimotlar')], max_length=100, null=True, verbose_name='Events')),
                ('events_ru', models.CharField(choices=[('ekspeditsiya', 'Ekspeditsiya'), ('konferensiyalar', 'konferensiya'), ('amaliy seminar', 'Amaliy seminar'), ('geologik sayohatlar', 'Geologik sayohatlar'), ('vebinarlar', 'Vebinarlar'), ('kashfiyotlar', 'Kashfiyotlar'), ('treninglar', 'Treninglar'), ('forumlar', 'Forumlar'), ('ilmiy taqdimotlar', 'Ilmiy taqdimotlar')], max_length=100, null=True, verbose_name='Events')),
                ('events_en', models.CharField(choices=[('ekspeditsiya', 'Ekspeditsiya'), ('konferensiyalar', 'konferensiya'), ('amaliy seminar', 'Amaliy seminar'), ('geologik sayohatlar', 'Geologik sayohatlar'), ('vebinarlar', 'Vebinarlar'), ('kashfiyotlar', 'Kashfiyotlar'), ('treninglar', 'Treninglar'), ('forumlar', 'Forumlar'), ('ilmiy taqdimotlar', 'Ilmiy taqdimotlar')], max_length=100, null=True, verbose_name='Events')),
                ('created_at', models.DateField(verbose_name='Created At')),
                ('image', models.ImageField(default='rasm.png', upload_to='projects/images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'News Image',
                'verbose_name_plural': 'News Images',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('comment_uz', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('comment_ru', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('comment_en', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
