# Generated by Django 4.2.18 on 2025-02-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_uz',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name_uz',
        ),
    ]
